/**
 * Onboard a new salon (tenant) — the «подключу за час» path.
 *
 *   node scripts/onboard.ts salon.json            # writes SQL + prints the admin token
 *   node scripts/onboard.ts salon.json --apply    # ...and runs it against the remote D1
 *
 * See launch/salon-example.json for the input shape. The script validates hours and
 * service durations BEFORE writing anything, so a bad config fails here rather than
 * halfway through the database.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { randomBytes, createHash } from "node:crypto";
import { assertServiceDuration, parseWorkingHours } from "../src/config";

interface SalonInput {
  slug: string;
  name: string;
  assistant_name?: string;
  address?: string;
  tz?: string;
  working_hours: Record<string, Array<[string, string]>>;
  slot_step_min?: number;
  buffer_min?: number;
  booking_horizon_days?: number;
  masters: Array<{ name: string; role?: string }>;
  services: Array<{ name: string; master: string; duration_min: number; price_kzt?: number | null; price_from?: boolean }>;
  limits?: Record<string, number>;
  tg_bot_token?: string;
}

const sq = (s: string): string => `'${String(s).replace(/'/g, "''")}'`;

function main(): void {
  const [file, ...flags] = process.argv.slice(2);
  if (!file) throw new Error("usage: node scripts/onboard.ts <salon.json> [--apply]");
  const cfg = JSON.parse(readFileSync(file, "utf8")) as SalonInput;

  // ---- validate before touching anything ----
  if (!/^[a-z0-9-]{3,40}$/.test(cfg.slug)) throw new Error(`slug must be kebab-case: ${cfg.slug}`);
  const step = cfg.slot_step_min ?? 30;
  parseWorkingHours(JSON.stringify(cfg.working_hours)); // throws ConfigError on bad hours
  const masterNames = new Set(cfg.masters.map((m) => m.name));
  for (const s of cfg.services) {
    if (!masterNames.has(s.master)) throw new Error(`service «${s.name}» references unknown master «${s.master}»`);
    assertServiceDuration(s.duration_min, step); // must be a multiple of the slot step
  }

  const adminToken = randomBytes(16).toString("hex");
  const adminHash = createHash("sha256").update(adminToken).digest("hex");
  const botId = cfg.tg_bot_token ? Number(cfg.tg_bot_token.split(":")[0]) : null;

  const lines: string[] = [];
  lines.push(`-- Onboarding «${cfg.name}» (${cfg.slug}). Generated by scripts/onboard.ts.`);
  lines.push(
    `INSERT INTO businesses (slug, name, assistant_name, address, tz, working_hours, slot_step_min, buffer_min, booking_horizon_days, tg_bot_id, tg_bot_token, admin_token_hash, crm_config, limits, is_demo) VALUES (` +
      [
        sq(cfg.slug),
        sq(cfg.name),
        sq(cfg.assistant_name ?? "Айым"),
        sq(cfg.address ?? ""),
        sq(cfg.tz ?? "Asia/Almaty"),
        sq(JSON.stringify(cfg.working_hours)),
        String(step),
        String(cfg.buffer_min ?? 0),
        String(cfg.booking_horizon_days ?? 14),
        botId ? String(botId) : "NULL",
        cfg.tg_bot_token ? sq(cfg.tg_bot_token) : "NULL",
        sq(adminHash),
        sq("{}"),
        sq(JSON.stringify(cfg.limits ?? {})),
        "0", // a real salon is never is_demo: nightly resetDemo must not touch it
      ].join(", ") +
      `);`,
  );
  // Resolve ids relative to the row we just inserted, so this works on any database.
  for (const m of cfg.masters) {
    lines.push(
      `INSERT INTO resources (business_id, name, role) SELECT id, ${sq(m.name)}, ${sq(m.role ?? "")} FROM businesses WHERE slug = ${sq(cfg.slug)};`,
    );
  }
  for (const s of cfg.services) {
    lines.push(
      `INSERT INTO services (business_id, resource_id, name, duration_min, price_kzt, price_from) ` +
        `SELECT b.id, r.id, ${sq(s.name)}, ${s.duration_min}, ${s.price_kzt == null ? "NULL" : s.price_kzt}, ${s.price_from ? 1 : 0} ` +
        `FROM businesses b JOIN resources r ON r.business_id = b.id AND r.name = ${sq(s.master)} WHERE b.slug = ${sq(cfg.slug)};`,
    );
  }

  const sqlPath = `/tmp/onboard-${cfg.slug}.sql`;
  writeFileSync(sqlPath, lines.join("\n") + "\n");

  console.log(`SQL written to ${sqlPath} (${cfg.masters.length} masters, ${cfg.services.length} services)`);
  console.log(`\nADMIN TOKEN for «${cfg.name}» — give it to the owner, it is shown once:\n  ${adminToken}\n`);

  if (flags.includes("--apply")) {
    console.log("applying to remote D1...");
    const out = execFileSync("npx", ["wrangler", "d1", "execute", "aiym-db", "--remote", "-y", `--file=${sqlPath}`], {
      encoding: "utf8",
    });
    console.log(out.includes('"success": true') ? "applied ✓" : out.slice(-400));
  } else {
    console.log(`To apply:\n  npx wrangler d1 execute aiym-db --remote -y --file=${sqlPath}`);
  }
  console.log(`\nNext: point the salon's bot at the webhook —`);
  console.log(`  curl "https://aiym.faizov-midat.workers.dev/api/tg/setup?secret=<WEBHOOK_SECRET>&biz=${cfg.slug}"`);
  console.log(`Then the owner sends the bot:  /owner ${adminToken}`);
}

main();
